//BASICAMENTE A PROGAMAÇÃO EM EVENTOS TEM COMO BASE OS DELEGADOS, SEU OBJETIVO É USAR OS DELEGADOS PARA ARMAZENAR UM OU MAIS MÉTODS QUE SERÃO ACIONADOS DEPENDENDO DA AÇÃO DO SISTEMA, USUARIO, ETC... OU SEJA O PRIMEIRO PASSO PARA PROGAMAR EM EVENTOS É CRIAR UM DELEGADO OU USAR UM PRE DEIFINIDO:

// ALGO QUE VALE A PENA RESSALTAR ANTES É QUE EVENTOS PODE SER O CLIQUE DO MOUSE, UMA TECLA PRESSIONADA, OU ALGO NO SISTEMA QUE O PROVOQUE, OU SEJA SÃO MÉTODOS QUE QUANDO ACIONADOS POR ALGO GERARAM OUTROS MÉTODOS QUE SERIAM A AÇÃO DO EVENTO, PERCEBA O NÍVEL DE ABSTRAÇÃO!

public delegate void MeuEventoHandler(string mensagem);

//O PRIMEIRO PASSO FOI CRIAR UM DELEGADO, AGORA DEVEMOS DECLARAR UM EVENTO, PARA ISTO USAMOS UMA CLASSE COM MÉTODOS:
public class Publicador
{
    // PERCEBA QUE EVENTO É UM TIPO E PERCEBA QUE O DELEGADO É PASSADO JUNTAMNETE COM ESTE TIPO COMO UM PARAMETRO DA NOSSA CLASSE:
    public event MeuEventoHandler EventoDisparado;

    public void AcionarEvento()
    {
        if (EventoDisparado != null)
        {
            EventoDisparado("O evento foi disparado!"); // AQUI É UM MÉTODO REPRESENTATIVO QUE JUSTAMNETE INDENTIFICA QUE O PARAMETRO DO TIPO EVENTIO NÃO ESTÁ VAZIO O QUE SIGNIFICA QUE O EVENTO FOI DISPARADO.
        }
    }
}

//APÓS ISSO TUDO PRECISAMOS CRIAR UM ASSINANTE QUE NÃO É NADA MAIS QUE A AÇÃO QUE IRÁ ACONTECER CASO O EVENTO ACONTEÇA:
public class Assinante
{
    public void QuandoEventoDisparado(string msg)
    {
        Console.WriteLine("Recebido: " + msg);
    }
}
// PERCEBA NOVAMENTE QUE É APENAS UMA CLASSE COM MÉTODOS, NADA NOVO.
// NO CASO A NOSSA AÇÃO AQUI É APENAS MOSTRAR UMA MENSSAGEM

//AGORA VAMOS EXECUTAR NO PROGAMA:
class Program
{
    static void Main()
    {
        Publicador pub = new Publicador();
        Assinante sub = new Assinante();

        // Assinando o evento
        pub.EventoDisparado += sub.QuandoEventoDisparado; // O QUE OCORRE AQUI É QUE O DELEGADO VAI RECEBER O MÉTODO DE AÇÃO, OU SEJA ESTAMOS ARMAZENANDO UM MÉTODO DENTRO DO PARAMETRO DO TIPO EVENTO.

        // Disparando o evento
        pub.AcionarEvento(); // ESTE MÉTODO ACIONAR (DISPARA) O EVENTO.
    }
}

//UM BÔNUS, EM INTERFACE GRÁFICA POR EXEMPLO TERIAMOS ESTE CASO:
meuBotao.Click += MeuMetodo; // O QUE OCORRE AQUI É QUE TEMOS UM PARAMETRO DELEGADO DO TIPO EVENTO QUE ARMAZENA UM MÉTODO (AÇÃO) E SE TÃO PARAMETRO FOR ACIONANDO ELE EXECUTARA ESTE MÉTODO (AÇÃO).

//CASO ESTEJA CURIOSO O QUE ACONTECE POR DEBAIXO DOS PANOS É ISSO:
EventoDisparado = (MeuEventoHandler)Delegate.Combine(EventoDisparado, new MeuEventoHandler(sub.QuandoEventoDisparado));

//CASO NECESSÁRIO PODE SE REMOVER AÇÕES:
pub.EventoDisparado -= sub.QuandoEventoDisparado;

