using System;
using System.Security.Cryptography; //NOME DA CLASSE NECESSÁRIA PARA USAR O SHA-256.
using System.Text;

class Program
{
    static void Main()
    {
        string senha = "minhaSenha123"; //SENHA QUE SERÁ HASHEADA

        string resultado; //RESULTADO QUE SERÁ GERADO SERÁ ARMAZENADO AQUI

        using (SHA256 sha256 = SHA256.Create()) //ATRAVÉZ DO USING IREMOS USAR ESTE OBJETO INSTANCIADO E DEPOIS DISCARTALO AO FINAL DO ESCOPO, O DESCARTE SERÁ AUTOMATICO NO USING.
        {
            byte[] bytes = Encoding.UTF8.GetBytes(senha); // AQUI PEGAMOS A VERSÃO EM BINARIOS DO NOSSO TEXTO EM STRING, POIS, EM C# SÓ SE É POSSÍVEL TRANSFORMAR CÓDIGOS BINARIOS EM HASHES. ALIÁS ESTAMOS SALVANDO EM UM ARRAY DO TIPO BYTE.

            byte[] hash = sha256.ComputeHash(bytes); //ATARVÉS DO MÉTODO DA CLASSE SHA256 ESTAMOS TRANSFORMANDO EM HASH O NOSSO CÓDIGO BINARIO E TAMBÉM ARMAZENANDO EM OUTRO ARRAY DO TIPO BYTE.

            resultado = BitConverter.ToString(hash).Replace("-", "").ToLower(); //AGORA PARA ENCERRAR CONVERTEMOS NOVAMNETE O HASH EM STRING USANDO A CLASSE BITCONVERTER EM UM STRING. CURIOSIDADE: SE NÃO USARMOS O REPLACE() PARA ELIMINAR OS TRAÇOS E O TOLOWER() PARA ELIMINAR AS LETRAS MAIÚSUCLAS O RESULTADO QUE SAÍ É ESSE: Hash SHA-256: 2C-48-81-AC-0B-8D-78-6B-71-19-C0-C0-C3-1D-C4-3D-ED-39-F5-9E-45-70-8C-12-E0-31-36-AC-DC-5F-F8-91

        }// A NECESSIADADE DE UM USING SE DÁ DEVIDO AO FATO DE QUE A CLASSE SHA256 É UMA CLASSE ABSTRATA LOGO O C# NÃO CONSEGUE LIMPAR APÓS O ENCERRAMENTO DO PROGAMA ASSIM COMO ELE FAZ COM OS OUTROS ELEMENTOS, DEVIDO A ISSO O CÓDIGO PODE FICAR PESADO, ENTÃO USAMOS O USING COM O OBJETIVO DE INDICAR AO C# QUE O OBJETO SHA256 DEVE SER LIMPADO ASSIM COMO OS OUTROS ELEMNTOS APÓS O ENCERRAMENTO DO PROGAMA.

        Console.WriteLine("Hash SHA-256: " + resultado);//O NOSSO HASH SE SALVO EM UMA VARIAVEL FORA DO ESCOPO, PODE SER USADO LIVREMENTE NO RESTO DO PROGAMA.
    }
}
